In [13]:
import os
import sys
import json
import glob
import numpy as np
from pathlib import Path

import pandas as pd
import pyarrow as pa

from fnmatch import fnmatch 

import tqdm

from natsort import natsorted, index_natsorted



sys.path.insert(0, '..')
from pali_text_models import get_engine, create_tables

pg_engine = get_engine()

In [2]:
import sys
from importlib import reload

sys.path.insert(0, '..')

import pali_text_models.models
reload(pali_text_models.models)

import pali_text_models
reload(pali_text_models)

from pali_text_models import get_session, SuttaTextModel

/Users/oceansxyz/.local/share/uv/tools/jupyter-core/lib/python3.12/site-packages/sqlmodel/main.py:682: SAWarning: This declarative base already contains a class with the same class name and module name as pali_text_models.models.SuttaTextModel, and will be replaced in the string-lookup table.
  DeclarativeMeta.__init__(cls, classname, bases, dict_, **kw)
/Users/oceansxyz/.local/share/uv/tools/jupyter-core/lib/python3.12/site-packages/sqlmodel/main.py:682: SAWarning: This declarative base already contains a class with the same class name and module name as pali_text_models.models.AbhidhammaTextModel, and will be replaced in the string-lookup table.
  DeclarativeMeta.__init__(cls, classname, bases, dict_, **kw)

In [11]:
from sqlmodel import SQLModel, Field, create_engine, Session
from typing import Optional, List, Dict
from sqlalchemy.dialects.postgresql import JSONB, ARRAY, FLOAT
from sqlalchemy.engine import Engine

### Load Sutta Texts

In [4]:
df = pd.read_csv('../pali_canon_hela.csv', index_col=0)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../pali_canon_hela.csv'

In [7]:
from pali_text_models import get_engine, create_tables

engine = get_engine()

# Create tables if they don't exist
create_tables(engine)

# Write DataFrame to PostgreSQL
df.to_sql(
    name='sutta_texts',
    con=engine,
    if_exists='replace',  # 'append' to add rows, 'replace' to overwrite
    index=True,
    index_label='index'
)

-1

### Load Abhidhamma

In [ ]:
df = pd.read_csv('../data/abhidhamma_text.csv', index_col=0)

df.rename(columns={'subchapter':'reading_unit_id'}, inplace=True)

df.to_sql(
    name='abhidhamma_texts',
    con=pg_engine,
    if_exists='replace',  # 'append' to add rows, 'replace' to overwrite
    index=True,
    index_label='index'
)

df.head()

,pakarana,chapter,reading_unit_id,text
verse_id,,,,
ds1.1:0.1,ds,ds1,ds1.1,Dhammasaṅgaṇī
ds2.1.1:87.2,ds,ds2,ds2.1.1,"Saddhindriyaṁ, vīriyindriyaṁ, satindriyaṁ, sam..."
ds2.1.1:87.1,ds,ds2,ds2.1.1,Katamāni tasmiṁ samaye aṭṭhindriyāni honti?
ds2.1.1:86.4,ds,ds2,ds2.1.1,Ime tasmiṁ samaye tayo āhārā honti.
ds2.1.1:86.3,ds,ds2,ds2.1.1,ayaṁ tasmiṁ samaye viññāṇāhāro hoti.

In [9]:
type(engine)

sqlalchemy.engine.base.Engine

In [12]:
def run_cypher(graph_name: str, cypher_query: str, engine: Engine):
    with Session(engine) as session:
        # AGE requires search_path
        session.exec(text('SET search_path = ag_catalog, "$user", public;'))

        wrapped = f"""
        SELECT * FROM cypher('{graph_name}', $$
        {cypher_query}
        $$) AS (result agtype);
        """

        result = session.exec(text(wrapped))
        rows = result.all()

        return [json.loads(r[0]) for r in rows]

     tablename
0  sutta_texts